# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-18 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título do Banner')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('image', models.ImageField(default='media/images/1.jpg', upload_to='banner/images', verbose_name='Foto do Banner')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Differential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Parceiro')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('image', models.ImageField(default='media/images/1.jpg', upload_to='differential/images', verbose_name='Ícone do Diferencial')),
            ],
            options={
                'verbose_name': 'Diferencial',
                'verbose_name_plural': 'Diferenciais',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(max_length=100, verbose_name='Parceiro')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('image', models.ImageField(default='media/images/1.jpg', upload_to='partner/images', verbose_name='Logo do Parceiro')),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
                'ordering': ['partner'],
            },
        ),
    ]
