# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-18 22:56
from __future__ import unicode_literals

from django.db import migrations
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=fontawesome.fields.IconField(blank=True, max_length=60, null=True, verbose_name='Ícone'),
        ),
    ]
