# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-19 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título do Slideshow')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('number', models.IntegerField(verbose_name='Número do slide (Ex.: 1, 2)')),
                ('image', models.ImageField(default='media/images/1.jpg', upload_to='slideshow/images', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Slideshow',
                'verbose_name_plural': 'Slideshows',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Título do Produto'),
        ),
    ]
