# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-22 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180219_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default='', max_length=500, verbose_name='Link da localização'),
        ),
    ]
