# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180227_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.CharField(default='question', max_length=10),
        ),
    ]
