# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180227_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='Outros', on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
    ]
